version: "3.9"

services:
  store:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server
    networks:
      - app_network

  backend:
    build: "./backend"
    volumes:
      - "./backend:/code"
    ports:
      - "8001:80"
    depends_on:
      - store
    networks:
      - app_network

  frontend:
    build: "./frontend"
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge